# 1. ???? ?? ???? ????? (?????????? ??????? ????? ??, ????????? hr_automation)
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_automation
# 2. ?????????? ??'? ??????????? ? Postgres ?? ?????????????
spring.datasource.username=postgres
# 3. ???? ????? ???? ?????? ??? POSTGRESQL (??????? "????_??????")
spring.datasource.password=239856

# ??????? ??? ??????
spring.datasource.driver-class-name=org.postgresql.Driver

# ???????????? Hibernate: ??????????? ??????????/?????????? ??????? ??? ??????? Java
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=public
# ?????????? ? ??????? SQL-??????, ??? Spring ?????? ?? ???? (???? ?????? ??? ????????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect