spring.datasource.url=jdbc:postgresql://localhost:5432/hr_automation
spring.datasource.username=postgres
spring.datasource.password=239856

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
# Вставляй сюди скопійований 16-значний пароль додатка від Google без пробілів
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true